### ISSUE TITLE
How is this different ?

### ISSUE THREAD

**Issue by Krammig** [snikket-im/snikket-android#61]
What differences does this have to Conversations ??

would be nice to know why this app exists and how it is better or different to Conversations ?

**Comment by mwild1** [comment]
If you are in any doubt, please just use Conversations :)

The functional differences between Snikket and Conversations are (intentionally) minimal. Mainly that Snikket does not allow registering on public XMPP servers.

Why the app exists, is because of https://snikket.org/about/goals/

The app is only intended for use with a Snikket instance on the server side. If you are looking for a general XMPP client, use the main Conversations project or another app instead.
